### PR TITLE
Remove extra GET request during patch

### PR DESCRIPTION
**Pull request by kumar303**
Was: https://github.com/mozilla/payments-service/pull/81

### CODE REVIEW

**Comment by kumar303** [comment]
whoops, Andy might have another patch in the works for this already

**Comment by andymckay** [comment]
The other patch is there, but there's still a question of how payments-service is going to enforce security, should it?

**Comment by andymckay** [comment]
Said patch is here: https://github.com/mozilla/solitude/pull/501

**Comment by kumar303** [comment]
I'm closing this PR because I do think we'll need the extra GET request. And, yes, I think the service should be responsible for making sure the logged in user owns the payment method that they are about to patch. Filed: https://github.com/mozilla/payments-service/issues/95

**Pull request closed without merging**
